version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      # Run the Python script
      - run:
          name: Run Python script
          command: |
            python C:/Users/panwa/PycharmProjects/pythonProject10/venv/Scripts/github_api.py

workflows:
  version: 2
  build:
    jobs:
      - build
