version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout

      # Install dependencies
      - run: pip install requests

      # Run tests
      - run: python github_api.py

workflows:
  version: 2
  build:
    jobs:
      - build
